#!/bin/bash
# Exit on command errors and treat unset variables as an error
set -eu

#=================================================
# GENERIC STARTING
#=================================================

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

if [ ! -e _common.sh ]; then
    # Get the functions file if not present in the current directory
    sudo cp ../settings/scripts/_common.sh ./_common.sh
    sudo chmod a+rx _common.sh
fi
source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

pvp=$(ynh_app_setting_get $app pvp)
damage=$(ynh_app_setting_get $app damage)
domain=$(ynh_app_setting_get $app domain)
creative=$(ynh_app_setting_get $app creative)
is_public=$(ynh_app_setting_get $app is_public)

#=================================================
# BACKUP STEPS
#=================================================
# RESTORE APT PREFERENCES AND SOURCES.LIST
#=================================================
ynh_restore_file "/etc/apt/sources.list.d/$app.list"

ynh_restore_file "/etc/apt/preferences.d/00MinetestPinning"

#=================================================
# INSTALL
#=================================================
if [ $(uname -m) == "armv7l" ]
then
    case "$codename" in
	wheezy)
	    add_repo_key 8B48AD6246925553 "7638 D044 2B90 D010"
	    ;;
	jessie)
	    add_repo_key 7638D0442B90D010 "7638 D044 2B90 D010"
	    ;;
	stretch)
	    add_repo_key E0B11894F66AEC98 "E0B1 1894 F66A EC98"
	    ;;
   esac
fi


ynh_package_update
ynh_install_app_dependencies minetest-server sqlite3

#=================================================
# ENABLE SERVICE IN ADMIN PANEL
#=================================================

# Add service to Yunohost's monitoring
yunohost service add minetest --log "/var/log/minetest/minetest.log"

#=================================================
# STOP MINETEST
#=================================================
service minetest-server stop

#=================================================
# CONFIGURATION
#=================================================
ynh_secure_remove "/etc/minetest/minetest.conf"
ynh_restore_file "/etc/minetest/minetest.conf"

#=================================================
# DATA
#=================================================
ynh_secure_remove "/var/games/minetest-server/"
ynh_restore_file "/var/games/minetest-server/"

ynh_restore_file "/tmp/map.sqlite"
echo ".restore /tmp/map.sqlite" | sqlite3 /var/games/minetest-server/.minetest/worlds/world/map.sqlite

#=================================================
# START MINETEST
#=================================================
service minetest-server start
